# Generated by Django 5.2.5 on 2025-08-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
