# Generated by Django 5.2.5 on 2025-08-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_payment_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='ads/header/'),
        ),
    ]
