# Generated by Django 5.2.5 on 2025-08-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='header_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
