# Generated by Django 5.2.5 on 2025-08-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_ad_header_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='adimage',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
