# Generated by Django 5.2.5 on 2025-08-09 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0010_user_rating_count_user_rating_sum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rating_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rating_sum',
        ),
    ]
