# Generated by Django 5.2.5 on 2025-08-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0012_chat_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('active', 'Active'), ('paused', 'Paused'), ('sold', 'Sold'), ('archived', 'Archived')], default='draft', help_text='Current status of the ad', max_length=20),
        ),
    ]
