# Generated by Django 5.2.5 on 2025-08-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0014_user_is_buyer_user_is_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_update',
            field=models.BooleanField(default=False),
        ),
    ]
