# Generated by Django 5.2.5 on 2025-08-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0015_user_avatar_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_completed',
            field=models.BooleanField(default=False, help_text='Whether profile has been completed and reward given.'),
        ),
    ]
