# Generated by Django 5.2.5 on 2025-08-11 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0019_order_viewhistory_savedad'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('message', 'Message'), ('payment', 'Payment')], db_index=True, default='message', max_length=30)),
                ('message_chat', models.TextField(blank=True, null=True)),
                ('message_chat_read', models.BooleanField(default=False)),
                ('message_chat_author_id', models.PositiveIntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('header', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='notifications/avatars/')),
                ('attachment', models.URLField(blank=True, null=True)),
                ('ad_id', models.PositiveIntegerField(blank=True, null=True)),
                ('seller_id', models.PositiveIntegerField(blank=True, null=True)),
                ('seller_name', models.CharField(blank=True, max_length=150, null=True)),
                ('seller_avatar_url', models.URLField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SellerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('message', 'Message'), ('payment', 'Payment'), ('new_order', 'New Order'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('order_cancelled', 'Order Cancelled'), ('ad_approved', 'Ad Approved'), ('ad_rejected', 'Ad Rejected')], db_index=True, default='message', max_length=30)),
                ('preferred_currency', models.CharField(choices=[('USD', 'US Dollar'), ('NGN', 'Nigerian Naira')], default='USD', help_text='Preferred currency for transaction info', max_length=3)),
                ('message_chat', models.TextField(blank=True, null=True)),
                ('message_chat_read', models.BooleanField(default=False)),
                ('message_chat_author_id', models.PositiveIntegerField(blank=True, null=True)),
                ('order_id', models.PositiveIntegerField(blank=True, null=True)),
                ('order_status', models.CharField(blank=True, max_length=50, null=True)),
                ('order_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('buyer_id', models.PositiveIntegerField(blank=True, null=True)),
                ('buyer_name', models.CharField(blank=True, max_length=150, null=True)),
                ('buyer_avatar_url', models.URLField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('header', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='notifications/avatars/')),
                ('attachment', models.URLField(blank=True, null=True)),
                ('ad_id', models.PositiveIntegerField(blank=True, null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
