# Generated by Django 5.2.5 on 2025-08-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0021_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='available_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='expected_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='is_willing_to_relocate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='portfolio_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
