# Generated by Django 5.2.5 on 2025-08-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0022_application_available_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
