# Generated by Django 5.2.5 on 2025-08-13 21:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0023_payment_payment_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Listing Fee', help_text='Optional name for this fee (eg: Basic Listing)', max_length=100)),
                ('currency', models.CharField(db_index=True, max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_default', models.BooleanField(default=False, help_text='If true and no match in requested currency, this will be used as fallback.')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('currency', 'name')},
            },
        ),
    ]
