# Generated by Django 5.2.5 on 2025-08-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0025_payment_checkout_url_payment_provider_payload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='client_secret_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='publishable_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
